fix test step

diff --git a/.github/workflows/pr-build.yml b/.github/workflows/pr-build.yml
--- a/.github/workflows/pr-build.yml
+++ b/.github/workflows/pr-build.yml
@@ -64,26 +64,26 @@ jobs:
       
       - name: Test
         run: |
-            xcodebuild clean test \
-              -project palautus.xcodeproj \
-              -scheme palautus \
-              -destination "platform=iOS Simulator,id=${SIMULATOR_UDID}" \
-              -sdk iphonesimulator \
-              -enableCodeCoverage YES \
-              CODE_SIGNING_REQUIRED=NO \
-              ONLY_ACTIVE_ARCH=YES \
-              -resultBundlePath TestResults \
-              -testPlan palautus \
-              -verbose \
-              | tee buildlog.txt \
-              | xcpretty && exit ${PIPESTATUS[0]}
+          xcodebuild clean test \
+            -project palautus.xcodeproj \
+            -scheme palautus \
+            -destination "platform=iOS Simulator,id=${SIMULATOR_UDID}" \
+            -sdk iphonesimulator \
+            -enableCodeCoverage YES \
+            CODE_SIGNING_REQUIRED=NO \
+            ONLY_ACTIVE_ARCH=YES \
+            -resultBundlePath TestResults \
+            -testPlan palautus \
+            -verbose \
+            | tee buildlog.txt \
+            | xcpretty && exit ${PIPESTATUS[0]}
 
-             # If tests fail, show the full log
-            if [ $? -ne 0 ]; then
-              echo "Tests failed. Full build log:"
-              cat buildlog.txt
-              exit 1
-            fi
+          # If tests fail, show the full log
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Full build log:"
+            cat buildlog.txt
+            exit 1
+          fi
 
       - name: Upload Test Results
         if: always()
